# Generated by Django 5.2.8 on 2026-05-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_date']},
        ),
    ]
