# Generated by Django 5.2.8 on 2026-05-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_post_categoy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoy',
            new_name='category',
        ),
    ]
